# Public records

Public records are the lifeblood of investigative reporting They carry their own philosophical framework, in a manner of speaking.  

* Sunlight is the best disinfectant. Corruption hides in the shadows.
* You paid for it with your taxes. It should be yours (with exceptions).
* Journalism with a capital J is about holding the powerful accountable for their actions.

Keeping those things in mind as you navigate public records is helpful.

## Federal law

Your access to public records and public meetings is a matter of the law. As a journalist, it is your job to know this law better than most lawyers. Which law applies depends on which branch of government you are asking. In addition to documents and other kinds of information, FOIA also provides access to structured datasets of the kind we'll use in this class. 

The Federal Government is covered by the Freedom of Information Act, or FOIA. FOIA is not a universal term. Do not use it if you are not talking to a federal agency. FOIA is a beacon of openness to the world. FOIA is deeply flawed and frustrating.

Why? 

* There is no real timetable with FOIA. Requests can take months, even years.
* As a journalist, you can ask that your request be expedited. 
* Guess what? That requires review. More delays.
* Exemptions are broad. National security, personal privacy, often overused.
* Denied? You can appeal. More delays.

The law was enacted in 1966, but it’s still poorly understood by most federal employees, if not outright flouted by political appointees. Lawsuits are common. 

Post 9/11, the Bush administration rolled back many agency rules. Obama ordered a "presumption of openness" but followed it with some of the most restrictive policies ever seen. The Trump Administration, similar to the Obama administration, claims to be the most transparent administration, but has steadily removed records from open access and broadly denied access to records. 

Result? FOIA is in trouble.

[SPJ is a good resource](https://www.spj.org/foi-guide-pros.asp). 

## State law

States are -- generally -- more open than the federal government. The distance between the government and the governed is smaller. Some states, like Florida and Texas, are very open. Others, like Virginia and Pennsylvania, are not. Maryland is somewhere in the middle. 

These laws generally give you license to view -- and obtain a copy of -- a record held by a state or local government agency.  

What is a public record? Generally speaking, public records are information stored on paper or in an electronic format held by a state or local government agency, but each state has its own list of types of records -- called "exemptions" -- that are not subject to disclosure. 

If a record has both exempt and non-exempt information mixed in, most states require an agency to disclose it after removing the exempt information, a process called "redaction." Agencies aren't required to create a record in order to fill your request. 

In some states but not all -- the public information law (or related case law) explicitly dictates that extracting a slice of a database doesn't constitute creation of a record. Most states can charge you a reasonable fee for time spent retrieving or copying records, though many have provisions to waive those fees for journalists. Every state law operates on a different timeline. Some only require agencies respond in a "reasonable" time, but others spell out exactly how fast an agency must respond to you, and how fast they must turn over the record.     

[The Reporters Committee For Freedom of the Press](https://www.rcfp.org/open-government-guide/) has a good resource for learning the law in your state. 

Please and thank you will get you more records than any lawyer or well written request. Be nice. Be polite. And be persistent. Following up regularly to check on status of a request lets an agency know they can't ignore you (and some will try). Hunting for records is like any other kind of reporting -- you have to do research. You have to ask questions. Ask them: What records do you keep? For how long? 

When requesting data, you are going to scare the press office and you are going to confuse the agency lawyer. Request to have their data person on the phone.

A good source of info? Records retention schedules, often required by law or administrative rule at an agency. Here's an example from [Nebraska](http://www.sos.ne.gov/records-management/retention_schedules.html). 
