# Geographic queries



```{r}
library(tidyverse)
library(sf)
library(janitor)
library(scales)
```


```{r}
hospitals <- st_read("data/Hospitals/Hospitals.shp")
```

```{r}
ne <- hospitals %>% filter(STATE == "NE")
```

```{r}
nehospitals <- ne %>% filter(TYPE == "CRITICAL ACCESS" | TYPE == "GENERAL ACUTE CARE")
```

```{r}
counties <- st_read("data/cb_2018_us_county_5m/cb_2018_us_county_5m.shp")
```

```{r}
necounties <- counties %>% filter(STATEFP == "31")
```

```{r}
nebedcount <- as.data.frame(nehospitals %>% filter(BEDS != -999) %>% group_by(COUNTY, COUNTYFIPS) %>% summarize(total_beds = sum(BEDS)) %>% rename(GEOID = COUNTYFIPS)) %>% select(-geometry)
```

```{r}
nehospbycounty <- necounties %>% left_join(nebedcount)
```


```{r}
ggplot() + geom_sf(data=nehospbycounty, aes(fill=total_beds)) + theme_minimal() + scale_fill_viridis_c(option = "plasma", trans = "sqrt")

```





```{r}
nebedcount %>% select(COUNTY, total_beds) %>% arrange(desc(total_beds)) 
```


```{r}
nebedcount %>% filter(COUNTY != "DOUGLAS" & COUNTY != "LANCASTER") %>% summarize(sum(total_beds))
```


```{r}
library(tidycensus)
```

```{r}
nepop <- get_acs(geography = "county", 
              variables = c(population = "B01003_001"), 
              state = "NE", 
              year = 2018)
```




```{r}
nehospbycounty <- nehospbycounty %>% inner_join(nepop, by="GEOID") %>% mutate(bedper1000 = (total_beds/estimate)*1000)
```

```{r}
ggplot() + geom_sf(data=nehospbycounty, aes(fill=bedper1000)) + theme_minimal() + scale_fill_viridis_c(option = "plasma", trans = "sqrt")
```

```{r}
as.data.frame(nehospbycounty %>% select(NAME.x, bedper1000) %>% arrange(desc(bedper1000)))
```
