--- 
title: "Data Journalism with R and the Tidyverse"
author: "Matt Waite"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: []
biblio-style: apalike
link-citations: yes
github-repo: 
description: "This is a book built on a very opinionated philosophy for undergraduate journalism students in doing data journalism in R with replicable methods."
---

# Introduction

## Data journalism history

## Modern data journalism

## Installations

This book is all in the R statistical language. To follow along, you'll do the following:

1. Install the R language on your computer. Go to the [R Project website](https://www.r-project.org/), click download R and select a mirror closest to your location. Then download the version for your computer. 

2. Install [R Studio Desktop](https://www.rstudio.com/products/rstudio/#Desktop). The free version is great. 

Going forward, you'll see passages like this:

```{r eval=FALSE}
install.packages("tidyverse")
```

That is code that you'll need to run in your R Studio. When you see that, you'll know what to do.

## About this book

This book is the collection of class materials for the author's Data Journalism class at the University of Nebraska-Lincoln's College of Journalism and Mass Communications. There's some things you should know about it:

* It is free for students. 
* The topics will remain the same but the text is going to be constantly tinkered with. 
* What is the work of the author is copyright Matt Waite 2020.
* The text is [Attribution-NonCommercial-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) Creative Commons licensed. That means you can share it and change it, but only if you share your changes with the same license and it cannot be used for commercial purposes. I'm not making money on this so you can't either.  
* As such, the whole book -- authored in Bookdown -- is [open sourced on Github](https://github.com/mattwaite/sportsdatabook). Pull requests welcomed! 

## What we'll cover

* Public records and open data
* R Basics
* Replication
* Data basics and structures
* Aggregates
* Mutating
* Filters
* Data smells
* Cleaning data I
* Cleaning data II
* Pulling data from PDFs
* Advanced analysis: Correlations and regressions
* Advanced analysis: Logistic regression
* Basic data scraping
* Intermediate data scraping
* Getting data from APIs: Census
* Visualizing for reporting: Basics
* Visualizing for reporting: More forms
* Visualizing for reporting: Faceting
* Geographic data basics
* Geographic queries
* Geographic visualization
* Text analysis basics
* Text analysis
* Writing with and about data
* Data journalism ethics
