<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 24 Basic Stats: The T-Test | Data Journalism with R and the Tidyverse</title>
  <meta name="description" content="This is a book built on a very opinionated philosophy for journalism students doing data journalism in R with replicable methods." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 24 Basic Stats: The T-Test | Data Journalism with R and the Tidyverse" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a book built on a very opinionated philosophy for journalism students doing data journalism in R with replicable methods." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 24 Basic Stats: The T-Test | Data Journalism with R and the Tidyverse" />
  
  <meta name="twitter:description" content="This is a book built on a very opinionated philosophy for journalism students doing data journalism in R with replicable methods." />
  

<meta name="author" content="Matt Waite (original author); updated by Derek Willis and Sean Mussenden" />


<meta name="date" content="2021-08-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="automating-geographic-analysis.html"/>
<link rel="next" href="an-intro-to-text-analysis.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.18/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160712129-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160712129-1');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="http://smussenden.github.io/coursefiles/data_journalism_book/">Data Journalism With R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#modern-data-journalism"><i class="fa fa-check"></i><b>1.1</b> Modern data journalism</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#installations"><i class="fa fa-check"></i><b>1.2</b> Installations</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#about-this-book"><i class="fa fa-check"></i><b>1.3</b> About this book</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#what-well-cover"><i class="fa fa-check"></i><b>1.4</b> What we’ll cover</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="public-records.html"><a href="public-records.html"><i class="fa fa-check"></i><b>2</b> Public records</a>
<ul>
<li class="chapter" data-level="2.1" data-path="public-records.html"><a href="public-records.html#federal-law"><i class="fa fa-check"></i><b>2.1</b> Federal law</a></li>
<li class="chapter" data-level="2.2" data-path="public-records.html"><a href="public-records.html#state-law"><i class="fa fa-check"></i><b>2.2</b> State law</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>3</b> R basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r-basics.html"><a href="r-basics.html#about-libraries"><i class="fa fa-check"></i><b>3.1</b> About libraries</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html"><i class="fa fa-check"></i><b>4</b> Data journalism in the age of replication</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html#the-stylebook"><i class="fa fa-check"></i><b>4.1</b> The stylebook</a></li>
<li class="chapter" data-level="4.2" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html#replication"><i class="fa fa-check"></i><b>4.2</b> Replication</a></li>
<li class="chapter" data-level="4.3" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html#goodbye-excel"><i class="fa fa-check"></i><b>4.3</b> Goodbye Excel?</a></li>
<li class="chapter" data-level="4.4" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html#receptivity-is-high"><i class="fa fa-check"></i><b>4.4</b> “Receptivity … is high”</a></li>
<li class="chapter" data-level="4.5" data-path="data-journalism-in-the-age-of-replication.html"><a href="data-journalism-in-the-age-of-replication.html#replication-in-notebooks"><i class="fa fa-check"></i><b>4.5</b> Replication in notebooks</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html"><i class="fa fa-check"></i><b>5</b> Data, structures and types</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#a-mental-picture"><i class="fa fa-check"></i><b>5.1</b> A Mental Picture</a></li>
<li class="chapter" data-level="5.2" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#types"><i class="fa fa-check"></i><b>5.2</b> Types</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="aggregates.html"><a href="aggregates.html"><i class="fa fa-check"></i><b>6</b> Aggregates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="aggregates.html"><a href="aggregates.html#libraries"><i class="fa fa-check"></i><b>6.1</b> Libraries</a></li>
<li class="chapter" data-level="6.2" data-path="aggregates.html"><a href="aggregates.html#importing-data"><i class="fa fa-check"></i><b>6.2</b> Importing data</a></li>
<li class="chapter" data-level="6.3" data-path="aggregates.html"><a href="aggregates.html#group-by-and-count"><i class="fa fa-check"></i><b>6.3</b> Group by and count</a></li>
<li class="chapter" data-level="6.4" data-path="aggregates.html"><a href="aggregates.html#other-summarization-methods-summing-mean-median-min-and-max"><i class="fa fa-check"></i><b>6.4</b> Other summarization methods: summing, mean, median, min and max</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="mutating-data.html"><a href="mutating-data.html"><i class="fa fa-check"></i><b>7</b> Mutating data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="mutating-data.html"><a href="mutating-data.html#another-use-of-mutate"><i class="fa fa-check"></i><b>7.1</b> Another use of mutate</a></li>
<li class="chapter" data-level="7.2" data-path="mutating-data.html"><a href="mutating-data.html#a-more-powerful-use"><i class="fa fa-check"></i><b>7.2</b> A more powerful use</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="working-with-dates.html"><a href="working-with-dates.html"><i class="fa fa-check"></i><b>8</b> Working with dates</a>
<ul>
<li class="chapter" data-level="8.1" data-path="working-with-dates.html"><a href="working-with-dates.html#the-hard-way"><i class="fa fa-check"></i><b>8.1</b> The hard way</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="filters-and-selections.html"><a href="filters-and-selections.html"><i class="fa fa-check"></i><b>9</b> Filters and selections</a>
<ul>
<li class="chapter" data-level="9.1" data-path="filters-and-selections.html"><a href="filters-and-selections.html#combining-filters"><i class="fa fa-check"></i><b>9.1</b> Combining filters</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="data-cleaning-part-i-data-smells.html"><a href="data-cleaning-part-i-data-smells.html"><i class="fa fa-check"></i><b>10</b> Data Cleaning Part I: Data smells</a>
<ul>
<li class="chapter" data-level="10.1" data-path="data-cleaning-part-i-data-smells.html"><a href="data-cleaning-part-i-data-smells.html#wrong-type"><i class="fa fa-check"></i><b>10.1</b> Wrong Type</a></li>
<li class="chapter" data-level="10.2" data-path="data-cleaning-part-i-data-smells.html"><a href="data-cleaning-part-i-data-smells.html#missing-data"><i class="fa fa-check"></i><b>10.2</b> Missing Data</a></li>
<li class="chapter" data-level="10.3" data-path="data-cleaning-part-i-data-smells.html"><a href="data-cleaning-part-i-data-smells.html#gaps-in-data"><i class="fa fa-check"></i><b>10.3</b> Gaps in data</a></li>
<li class="chapter" data-level="10.4" data-path="data-cleaning-part-i-data-smells.html"><a href="data-cleaning-part-i-data-smells.html#supicious-outliers"><i class="fa fa-check"></i><b>10.4</b> Supicious Outliers</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="data-cleaning-part-ii-janitor.html"><a href="data-cleaning-part-ii-janitor.html"><i class="fa fa-check"></i><b>11</b> Data Cleaning Part II: Janitor</a>
<ul>
<li class="chapter" data-level="11.1" data-path="data-cleaning-part-ii-janitor.html"><a href="data-cleaning-part-ii-janitor.html#cleaning-headers"><i class="fa fa-check"></i><b>11.1</b> Cleaning headers</a></li>
<li class="chapter" data-level="11.2" data-path="data-cleaning-part-ii-janitor.html"><a href="data-cleaning-part-ii-janitor.html#changing-data-types"><i class="fa fa-check"></i><b>11.2</b> Changing data types</a></li>
<li class="chapter" data-level="11.3" data-path="data-cleaning-part-ii-janitor.html"><a href="data-cleaning-part-ii-janitor.html#duplicates"><i class="fa fa-check"></i><b>11.3</b> Duplicates</a></li>
<li class="chapter" data-level="11.4" data-path="data-cleaning-part-ii-janitor.html"><a href="data-cleaning-part-ii-janitor.html#cleaning-strings"><i class="fa fa-check"></i><b>11.4</b> Cleaning strings</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="data-cleaning-part-iii-open-refine.html"><a href="data-cleaning-part-iii-open-refine.html"><i class="fa fa-check"></i><b>12</b> Data Cleaning Part III: Open Refine</a>
<ul>
<li class="chapter" data-level="12.1" data-path="data-cleaning-part-iii-open-refine.html"><a href="data-cleaning-part-iii-open-refine.html#refinr-open-refine-in-r"><i class="fa fa-check"></i><b>12.1</b> Refinr, Open Refine in R</a></li>
<li class="chapter" data-level="12.2" data-path="data-cleaning-part-iii-open-refine.html"><a href="data-cleaning-part-iii-open-refine.html#manually-cleaning-data-with-open-refine"><i class="fa fa-check"></i><b>12.2</b> Manually cleaning data with Open Refine</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="cleaning-data-part-iv-pdfs.html"><a href="cleaning-data-part-iv-pdfs.html"><i class="fa fa-check"></i><b>13</b> Cleaning Data Part IV: PDFs</a>
<ul>
<li class="chapter" data-level="13.1" data-path="cleaning-data-part-iv-pdfs.html"><a href="cleaning-data-part-iv-pdfs.html#easy-does-it"><i class="fa fa-check"></i><b>13.1</b> Easy does it</a></li>
<li class="chapter" data-level="13.2" data-path="cleaning-data-part-iv-pdfs.html"><a href="cleaning-data-part-iv-pdfs.html#when-it-looks-good-but-needs-a-little-fixing"><i class="fa fa-check"></i><b>13.2</b> When it looks good, but needs a little fixing</a></li>
<li class="chapter" data-level="13.3" data-path="cleaning-data-part-iv-pdfs.html"><a href="cleaning-data-part-iv-pdfs.html#cleaning-up-the-data-in-r"><i class="fa fa-check"></i><b>13.3</b> Cleaning up the data in R</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="combining-and-joining.html"><a href="combining-and-joining.html"><i class="fa fa-check"></i><b>14</b> Combining and joining</a>
<ul>
<li class="chapter" data-level="14.1" data-path="combining-and-joining.html"><a href="combining-and-joining.html#combining-data-stacking"><i class="fa fa-check"></i><b>14.1</b> Combining data (stacking)</a></li>
<li class="chapter" data-level="14.2" data-path="combining-and-joining.html"><a href="combining-and-joining.html#joining-data"><i class="fa fa-check"></i><b>14.2</b> Joining data</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="scraping-data-with-rvest.html"><a href="scraping-data-with-rvest.html"><i class="fa fa-check"></i><b>15</b> Scraping data with Rvest</a>
<ul>
<li class="chapter" data-level="15.1" data-path="scraping-data-with-rvest.html"><a href="scraping-data-with-rvest.html#a-more-difficult-example"><i class="fa fa-check"></i><b>15.1</b> A more difficult example</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="advanced-rvest.html"><a href="advanced-rvest.html"><i class="fa fa-check"></i><b>16</b> Advanced rvest</a></li>
<li class="chapter" data-level="17" data-path="intro-to-apis-the-census.html"><a href="intro-to-apis-the-census.html"><i class="fa fa-check"></i><b>17</b> Intro to APIs: The Census</a>
<ul>
<li class="chapter" data-level="17.1" data-path="intro-to-apis-the-census.html"><a href="intro-to-apis-the-census.html#the-acs"><i class="fa fa-check"></i><b>17.1</b> The ACS</a></li>
<li class="chapter" data-level="17.2" data-path="intro-to-apis-the-census.html"><a href="intro-to-apis-the-census.html#bonus-api-example-coronavirus"><i class="fa fa-check"></i><b>17.2</b> Bonus API example: Coronavirus</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="visualizing-your-data-for-reporting.html"><a href="visualizing-your-data-for-reporting.html"><i class="fa fa-check"></i><b>18</b> Visualizing your data for reporting</a>
<ul>
<li class="chapter" data-level="18.1" data-path="visualizing-your-data-for-reporting.html"><a href="visualizing-your-data-for-reporting.html#bar-charts"><i class="fa fa-check"></i><b>18.1</b> Bar charts</a></li>
<li class="chapter" data-level="18.2" data-path="visualizing-your-data-for-reporting.html"><a href="visualizing-your-data-for-reporting.html#line-charts"><i class="fa fa-check"></i><b>18.2</b> Line charts</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="visualizing-your-data-for-publication.html"><a href="visualizing-your-data-for-publication.html"><i class="fa fa-check"></i><b>19</b> Visualizing your data for publication</a>
<ul>
<li class="chapter" data-level="19.1" data-path="visualizing-your-data-for-publication.html"><a href="visualizing-your-data-for-publication.html#datawrapper"><i class="fa fa-check"></i><b>19.1</b> Datawrapper</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="geographic-data-basics.html"><a href="geographic-data-basics.html"><i class="fa fa-check"></i><b>20</b> Geographic data basics</a>
<ul>
<li class="chapter" data-level="20.1" data-path="geographic-data-basics.html"><a href="geographic-data-basics.html#importing-and-viewing-data"><i class="fa fa-check"></i><b>20.1</b> Importing and viewing data</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="geographic-analysis.html"><a href="geographic-analysis.html"><i class="fa fa-check"></i><b>21</b> Geographic analysis</a>
<ul>
<li class="chapter" data-level="21.1" data-path="geographic-analysis.html"><a href="geographic-analysis.html#why-tidycensus-is-so-useful"><i class="fa fa-check"></i><b>21.1</b> Why tidycensus is so useful</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="automating-analysis.html"><a href="automating-analysis.html"><i class="fa fa-check"></i><b>22</b> Automating analysis</a>
<ul>
<li class="chapter" data-level="22.1" data-path="automating-analysis.html"><a href="automating-analysis.html#automating-downloads-an-imports"><i class="fa fa-check"></i><b>22.1</b> Automating downloads an imports</a></li>
<li class="chapter" data-level="22.2" data-path="automating-analysis.html"><a href="automating-analysis.html#exploring-the-data"><i class="fa fa-check"></i><b>22.2</b> Exploring the data</a></li>
<li class="chapter" data-level="22.3" data-path="automating-analysis.html"><a href="automating-analysis.html#analysis"><i class="fa fa-check"></i><b>22.3</b> Analysis</a></li>
<li class="chapter" data-level="22.4" data-path="automating-analysis.html"><a href="automating-analysis.html#making-updating-graphics"><i class="fa fa-check"></i><b>22.4</b> Making updating graphics</a></li>
<li class="chapter" data-level="22.5" data-path="automating-analysis.html"><a href="automating-analysis.html#the-state-vs-the-feds"><i class="fa fa-check"></i><b>22.5</b> The State vs the Feds</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="automating-geographic-analysis.html"><a href="automating-geographic-analysis.html"><i class="fa fa-check"></i><b>23</b> Automating geographic analysis</a>
<ul>
<li class="chapter" data-level="23.1" data-path="automating-geographic-analysis.html"><a href="automating-geographic-analysis.html#mapping-continuously"><i class="fa fa-check"></i><b>23.1</b> Mapping continuously</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="basic-stats-the-t-test.html"><a href="basic-stats-the-t-test.html"><i class="fa fa-check"></i><b>24</b> Basic Stats: The T-Test</a>
<ul>
<li class="chapter" data-level="24.1" data-path="basic-stats-the-t-test.html"><a href="basic-stats-the-t-test.html#specific-call-types"><i class="fa fa-check"></i><b>24.1</b> Specific call types</a></li>
<li class="chapter" data-level="24.2" data-path="basic-stats-the-t-test.html"><a href="basic-stats-the-t-test.html#what-else-should-we-look-at"><i class="fa fa-check"></i><b>24.2</b> What else should we look at?</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="an-intro-to-text-analysis.html"><a href="an-intro-to-text-analysis.html"><i class="fa fa-check"></i><b>25</b> An intro to text analysis</a>
<ul>
<li class="chapter" data-level="25.1" data-path="an-intro-to-text-analysis.html"><a href="an-intro-to-text-analysis.html#going-further-by-analyzing-text"><i class="fa fa-check"></i><b>25.1</b> Going further by analyzing text</a></li>
<li class="chapter" data-level="25.2" data-path="an-intro-to-text-analysis.html"><a href="an-intro-to-text-analysis.html#going-beyond-a-single-word"><i class="fa fa-check"></i><b>25.2</b> Going beyond a single word</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="writing-with-numbers.html"><a href="writing-with-numbers.html"><i class="fa fa-check"></i><b>26</b> Writing with numbers</a>
<ul>
<li class="chapter" data-level="26.1" data-path="writing-with-numbers.html"><a href="writing-with-numbers.html#how-to-write-about-numbers-without-overwhelming-with-numbers."><i class="fa fa-check"></i><b>26.1</b> How to write about numbers without overwhelming with numbers.</a></li>
<li class="chapter" data-level="26.2" data-path="writing-with-numbers.html"><a href="writing-with-numbers.html#when-exact-numbers-matter"><i class="fa fa-check"></i><b>26.2</b> When exact numbers matter</a></li>
<li class="chapter" data-level="26.3" data-path="writing-with-numbers.html"><a href="writing-with-numbers.html#an-example"><i class="fa fa-check"></i><b>26.3</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html"><i class="fa fa-check"></i><b>27</b> Ethics in data journalism</a>
<ul>
<li class="chapter" data-level="27.1" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html#problems"><i class="fa fa-check"></i><b>27.1</b> Problems</a></li>
<li class="chapter" data-level="27.2" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html#the-googlebot"><i class="fa fa-check"></i><b>27.2</b> The Googlebot</a></li>
<li class="chapter" data-level="27.3" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html#data-lifetimes"><i class="fa fa-check"></i><b>27.3</b> Data Lifetimes</a></li>
<li class="chapter" data-level="27.4" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html#you-are-a-data-provider"><i class="fa fa-check"></i><b>27.4</b> You Are a Data Provider</a></li>
<li class="chapter" data-level="27.5" data-path="ethics-in-data-journalism.html"><a href="ethics-in-data-journalism.html#ethical-data"><i class="fa fa-check"></i><b>27.5</b> Ethical Data</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="using-github.html"><a href="using-github.html"><i class="fa fa-check"></i><b>28</b> Using GitHub</a>
<ul>
<li class="chapter" data-level="28.1" data-path="using-github.html"><a href="using-github.html#how-it-works"><i class="fa fa-check"></i><b>28.1</b> How It Works</a></li>
<li class="chapter" data-level="28.2" data-path="using-github.html"><a href="using-github.html#getting-started"><i class="fa fa-check"></i><b>28.2</b> Getting Started</a></li>
<li class="chapter" data-level="28.3" data-path="using-github.html"><a href="using-github.html#advanced-use"><i class="fa fa-check"></i><b>28.3</b> Advanced Use</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Journalism with R and the Tidyverse</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-stats-the-t-test" class="section level1" number="24">
<h1><span class="header-section-number">Chapter 24</span> Basic Stats: The T-Test</h1>
<p>During the coronavirus social distancing, former Lincoln Police Chief and Director of Public Safety Tom Casady tweeted the following:</p>
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr">
If you’re interested I how effective social distancing is working, a good surrogate measure would be the number of police incidents. Lincoln averages about 329 per day. <a href="https://t.co/tQAo7CN82r">https://t.co/tQAo7CN82r</a>
</p>
— Tom Casady (<span class="citation">(<a href="#ref-TCasady304" role="doc-biblioref"><strong>TCasady304?</strong></a>)</span>) <a href="https://twitter.com/TCasady304/status/1239696474813992962?ref_src=twsrc%5Etfw">March 16, 2020</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>So, is it?</p>
<p>Let’s find out. Can we see signs of Lincoln hunkering down in LPD data?</p>
<p>We’re fortunate here. We can get <a href="http://opendata.lincoln.ne.gov/datasets/lpd-dispatch-records">daily updated calls for service data from the Lincoln Open Data Portal</a>. So download the spreadsheet version (which is really a csv) and load some libraries.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="basic-stats-the-t-test.html#cb456-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb456-2"><a href="basic-stats-the-t-test.html#cb456-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb456-3"><a href="basic-stats-the-t-test.html#cb456-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<p>And now load the data.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="basic-stats-the-t-test.html#cb457-1" aria-hidden="true" tabindex="-1"></a>calls <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/LPD_Dispatch_Records.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 378324 Columns: 15</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (9): CASE_, RD, OFFICER, INC_, RPT_Time, NEIGHBOR, TEAM_AREA, CFS_LEGEND...
## dbl (6): X, Y, OBJECTID, LOC_CODE, RPT_Date, RPT_DOW</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>The first issue we need to address is that the dates don’t import as dates. So we need to fix RPT_Date to make it a date. Lubridate to the rescue.</p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="basic-stats-the-t-test.html#cb461-1" aria-hidden="true" tabindex="-1"></a>calls <span class="ot">&lt;-</span> calls <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">RPT_Date =</span> <span class="fu">ymd</span>(RPT_Date))</span></code></pre></div>
<pre><code>## Warning: 13 failed to parse.</code></pre>
<p>For purposes of this work, we can live without the 13 (they don’t occur when we’re interested in).</p>
<p>First, let’s just visualize regular call volumes and see: Does the end of the line drop sharply, indicating people are socially distancing?</p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="basic-stats-the-t-test.html#cb463-1" aria-hidden="true" tabindex="-1"></a>calls <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>RPT_Date, <span class="at">y=</span>total))</span></code></pre></div>
<pre><code>## Warning: Removed 1 row(s) containing missing values (geom_path).</code></pre>
<p><img src="datajournalism_files/figure-html/unnamed-chunk-266-1.png" width="672" /></p>
<p>Short answer? No. Longer answer? It’s obvious that Lincoln has a seasonality to crime. It generally is low over the dead of winter and rises as it gets warmer, peaking during early football season (no surprise there) and dropping back down as winter sets in. So to make this useful, we should only compare dates in this March to previous March dates. Then we eliminate the seasonality issue.</p>
<p>So we’re going to do some filtering here. The following block is broken down like this:</p>
<ol style="list-style-type: decimal">
<li>First, filter days in March.</li>
<li>Then, group calls by day.</li>
<li>Then, count them. How many happened that day?</li>
<li>Then we’re going to do some mutate magic. <code>case_when</code> is if/else logic. So what this says is if the date is less than March 16, 2020 – the day Lincoln’s mayor declared a local emergency – then it’s in the Previous group. After and equal to March 16, 2020, it’s in the Current group.</li>
<li>Last, but not least, cutting out April dates in this dataset. Just going to look at March.</li>
</ol>
<p>And we’ll put it all in a dataframe called <code>calldays</code>.</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="basic-stats-the-t-test.html#cb465-1" aria-hidden="true" tabindex="-1"></a>calldays <span class="ot">&lt;-</span> calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">month</span>(RPT_Date) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total_calls =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">TimePeriod =</span> <span class="fu">case_when</span>(</span>
<span id="cb465-2"><a href="basic-stats-the-t-test.html#cb465-2" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Previous&quot;</span>,</span>
<span id="cb465-3"><a href="basic-stats-the-t-test.html#cb465-3" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Current&quot;</span>,</span>
<span id="cb465-4"><a href="basic-stats-the-t-test.html#cb465-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-04-01&quot;</span>))</span></code></pre></div>
<p>To test if the current period of time is different from previous March days, we’re going to use something called a t-test. A t-test simply asks if two sample means are different – is the average between sample A different from the mean of sample B. It looks at the variability in the data and boils it down to a p-value. The p-value tells us if it’s statistically significant or not. Simply put: If our value is below .05, it’s statistically significant and the two means are different. If it’s above .05, then the differences between the two numbers are not meaningful – it could just be random chance that they’re different.</p>
<p><a href="https://conjointly.com/kb/statistical-student-t-test/">More on the t-test here</a>. Worth reading.</p>
<p>In R, a <code>t.test</code> is a base R function, owing to it being a statistical language. So were going to look at <code>total_calls</code> split between <code>TimePeriod</code>s. Here’s the code. We’ll interpret the output below.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="basic-stats-the-t-test.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(total_calls <span class="sc">~</span> TimePeriod, <span class="at">data =</span> calldays)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total_calls by TimePeriod
## t = -0.30291, df = 24.691, p-value = 0.7645
## alternative hypothesis: true difference in means between group Current and group Previous is not equal to 0
## 95 percent confidence interval:
##  -16.60408  12.34852
## sample estimates:
##  mean in group Current mean in group Previous 
##               295.7333               297.8611</code></pre>
<p>First, look at the two means on the bottom. On the left, it says the daily call average in the current group – March 16 to March 31 – is 295.73 calls per day. On the right, in previous March days, it’s 297.86. So about 2.3 calls difference. Is that a significant difference? Look above to the p-value for that answer. At 0.7645, that’s considerably higher than .05.</p>
<p>So, statistically speaking, these numbers are the same. There’s no real difference between them. A bad reporter would write a story – or a bad mayor would hold a press conference and shout from the heavens – that crime is down 2.3 calls per day on average! This is good! But it’s not real. It’s statistically meaningless. It’s just random noise.</p>
<div id="specific-call-types" class="section level2" number="24.1">
<h2><span class="header-section-number">24.1</span> Specific call types</h2>
<p>But you need only look outside your house to realize the world is different. So how is it that calls to Lincoln police aren’t?</p>
<p>As they say, the devil is in the details.</p>
<p>Let’s use <code>janitor</code>’s <code>tabyl</code> function to get a look at what kind of call groups we can look at.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="basic-stats-the-t-test.html#cb468-1" aria-hidden="true" tabindex="-1"></a>calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-01&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">tabyl</span>(CFS_LEGEND)</span></code></pre></div>
<pre><code>##                  CFS_LEGEND    n      percent
##                    ACCIDENT  585 0.0641166155
##                       ALARM  221 0.0242218325
##                     ALCOHOL  143 0.0156729505
##                       ARSON    2 0.0002192021
##                     ASSAULT  282 0.0309074967
##                    BURGLARY   98 0.0107409031
##                 DISTURBANCE 1654 0.1812801403
##                       DRUGS  232 0.0254274441
##                         DUI   47 0.0051512495
##                EMBEZZLEMENT    9 0.0009864095
##                        FIRE   36 0.0039456379
##                     FORGERY   47 0.0051512495
##                       FRAUD  161 0.0176457694
##                      HAZARD   97 0.0106313021
##           INDECENT EXPOSURE    4 0.0004384042
##                     MEDICAL  146 0.0160017536
##              MISSING PERSON  188 0.0206049978
##         MOTOR VEHICLE THEFT   48 0.0052608505
##                       OTHER 2629 0.2881411662
##                      PATROL    5 0.0005480053
##                 PORNOGRAPHY   11 0.0012056116
##           RECOVERED VEHICLE    2 0.0002192021
##                     ROBBERY   12 0.0013152126
##                  SUSPICIOUS  566 0.0620341955
##                       THEFT   94 0.0103024989
##          THEFT - AUTO PARTS   36 0.0039456379
##       THEFT - FROM BUILDING   82 0.0089872863
##  THEFT - FROM COIN OPERATED    3 0.0003288032
##        THEFT - FROM VEHICLE  266 0.0291538799
##      THEFT - POCKET PICKING    1 0.0001096011
##         THEFT - SHOPLIFTING  113 0.0123849189
##                     TRAFFIC  730 0.0800087681
##                 TRESPASSING  263 0.0288250767
##                   VANDALISM  203 0.0222490136
##                     WARRANT   91 0.0099736957
##             WEAPONS OFFENSE   17 0.0018632179</code></pre>
<p>Let’s first look at disturbances, one of the first big call types on that list. Disturbances, for those of you who have always stayed on the right side of the law, are anything where the police get called out to and people are acting the fool. Arguments between neighbors? Disturbance. Terrible racket coming from the back yard down the way? Disturbance. So it’s pretty generic and it happens a lot.</p>
<p>To look specifically at a crime, we’re going to take what we did before and add a filter into it, and we’ll name the dataframe what we’re looking at.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="basic-stats-the-t-test.html#cb470-1" aria-hidden="true" tabindex="-1"></a>disturbance <span class="ot">&lt;-</span> calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CFS_LEGEND <span class="sc">==</span> <span class="st">&quot;DISTURBANCE&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">month</span>(RPT_Date) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total_calls =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">TimePeriod =</span> <span class="fu">case_when</span>(</span>
<span id="cb470-2"><a href="basic-stats-the-t-test.html#cb470-2" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Previous&quot;</span>,</span>
<span id="cb470-3"><a href="basic-stats-the-t-test.html#cb470-3" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Current&quot;</span>,</span>
<span id="cb470-4"><a href="basic-stats-the-t-test.html#cb470-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-04-01&quot;</span>))</span></code></pre></div>
<p>Then we can do our t-test.</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="basic-stats-the-t-test.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(total_calls <span class="sc">~</span> TimePeriod, <span class="at">data =</span> disturbance)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total_calls by TimePeriod
## t = 2.7026, df = 19.753, p-value = 0.0138
## alternative hypothesis: true difference in means between group Current and group Previous is not equal to 0
## 95 percent confidence interval:
##   1.641788 12.787842
## sample estimates:
##  mean in group Current mean in group Previous 
##               56.06667               48.85185</code></pre>
<p>So what does this say? Typically, you’d see 48.85 disturbances a day on average before coronavirus. Now? 56. Is that a significant difference? According to our p-value of 0.0138, it is. So police are going to more disturbances than usual.</p>
<p>What about traffic calls?</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="basic-stats-the-t-test.html#cb473-1" aria-hidden="true" tabindex="-1"></a>traffic <span class="ot">&lt;-</span> calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CFS_LEGEND <span class="sc">==</span> <span class="st">&quot;TRAFFIC&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">month</span>(RPT_Date) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total_calls =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">TimePeriod =</span> <span class="fu">case_when</span>(</span>
<span id="cb473-2"><a href="basic-stats-the-t-test.html#cb473-2" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Previous&quot;</span>,</span>
<span id="cb473-3"><a href="basic-stats-the-t-test.html#cb473-3" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Current&quot;</span>,</span>
<span id="cb473-4"><a href="basic-stats-the-t-test.html#cb473-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-04-01&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="basic-stats-the-t-test.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(total_calls <span class="sc">~</span> TimePeriod, <span class="at">data =</span> traffic)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total_calls by TimePeriod
## t = -3.8869, df = 29.404, p-value = 0.0005338
## alternative hypothesis: true difference in means between group Current and group Previous is not equal to 0
## 95 percent confidence interval:
##  -13.308937  -4.135507
## sample estimates:
##  mean in group Current mean in group Previous 
##               23.33333               32.05556</code></pre>
<p>Typically get about 32 calls a day, now 23. That’s a big difference, and a statistically significant one.</p>
<p>How about car accidents?</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="basic-stats-the-t-test.html#cb476-1" aria-hidden="true" tabindex="-1"></a>accident <span class="ot">&lt;-</span> calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CFS_LEGEND <span class="sc">==</span> <span class="st">&quot;ACCIDENT&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">month</span>(RPT_Date) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total_calls =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">TimePeriod =</span> <span class="fu">case_when</span>(</span>
<span id="cb476-2"><a href="basic-stats-the-t-test.html#cb476-2" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Previous&quot;</span>,</span>
<span id="cb476-3"><a href="basic-stats-the-t-test.html#cb476-3" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Current&quot;</span>,</span>
<span id="cb476-4"><a href="basic-stats-the-t-test.html#cb476-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-04-01&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="basic-stats-the-t-test.html#cb477-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(total_calls <span class="sc">~</span> TimePeriod, <span class="at">data =</span> accident)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total_calls by TimePeriod
## t = -7.4616, df = 37.921, p-value = 0.000000005964
## alternative hypothesis: true difference in means between group Current and group Previous is not equal to 0
## 95 percent confidence interval:
##  -13.687940  -7.845393
## sample estimates:
##  mean in group Current mean in group Previous 
##               14.40000               25.16667</code></pre>
<p>Typically get a little more than 25 accident calls a day. Now, it’s 14.4. Insurance companies are making out like bandits right now.</p>
</div>
<div id="what-else-should-we-look-at" class="section level2" number="24.2">
<h2><span class="header-section-number">24.2</span> What else should we look at?</h2>
<p>With a little magic using <code>tidyr</code> to transform the data (<a href="http://mattwaite.github.io/sports/transforming-data.html">learn more about that here</a>), we can get a peek at other call groups worth exploring.</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="basic-stats-the-t-test.html#cb479-1" aria-hidden="true" tabindex="-1"></a>calls <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">month</span>(RPT_Date) <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(RPT_Date, CFS_LEGEND) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">total_calls =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">TimePeriod =</span> <span class="fu">case_when</span>(</span>
<span id="cb479-2"><a href="basic-stats-the-t-test.html#cb479-2" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Previous&quot;</span>,</span>
<span id="cb479-3"><a href="basic-stats-the-t-test.html#cb479-3" aria-hidden="true" tabindex="-1"></a>  RPT_Date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-03-16&quot;</span>) <span class="sc">~</span> <span class="st">&quot;Current&quot;</span>,</span>
<span id="cb479-4"><a href="basic-stats-the-t-test.html#cb479-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(RPT_Date <span class="sc">&lt;</span> <span class="fu">as.Date</span>(<span class="st">&quot;2020-04-01&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb479-5"><a href="basic-stats-the-t-test.html#cb479-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TimePeriod, CFS_LEGEND) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">avg_calls =</span> <span class="fu">mean</span>(total_calls)) <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">&quot;TimePeriod&quot;</span>, <span class="at">values_from =</span> <span class="st">&quot;avg_calls&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;RPT_Date&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;TimePeriod&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 35 × 3
##    CFS_LEGEND   Current Previous
##    &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;
##  1 ACCIDENT       14.4     25.2 
##  2 ALARM           7.87     7.56
##  3 ALCOHOL         4.33     6.02
##  4 ARSON           1        1.2 
##  5 ASSAULT         8.8     10.2 
##  6 BURGLARY        3.33     3.06
##  7 DISTURBANCE    56.1     48.9 
##  8 DRUGS           7.8      9.85
##  9 DUI             1.55     2.98
## 10 EMBEZZLEMENT    1.5      1.35
## # … with 25 more rows</code></pre>
<p>Other interesting stories here? DUI is almost half of what it normally is. Thefts from vehicles are up way up. Also: trespassing? What’s that about?</p>
<p>But are they meaningful differences? Put them to the test.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="automating-geographic-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="an-intro-to-text-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/23-basicstats.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["datajournalism.pdf", "datajournalism.epub"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
