---
title: "class_04_demonstration.Rmd"
author: "derek willis"
date: "8/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Points to hit
1. Review of third lab questions/problems.
2. Demonstration of combining and merging

## Load Libraries
```{r}
# turn off sci notation
options(scipen=999)
library(tidyverse)
library(lubridate)
```

## Combining data (stacking)

Let's say that we have county population estimates for three different years - [2010](https://umd.box.com/s/vsuyt7v1gtb2u0aerliv5eixfmzfgt17), [2015](https://umd.box.com/s/2qijnwfygsrfin9d2o1krhzw5o8vza30) and [2020](https://umd.box.com/s/uqkeaabkvs4ge0l10j3w3sa76q3z1v16) - in three different files. They have the same record layout and the same number of counties.

```{r}
popestimate_2010 <- read_csv("popestimate_2010.csv")
```

```{r}
popestimate_2015 <- read_csv("popestimate_2015.csv")
```

```{r}
popestimate_2020 <- read_csv("popestimate_2020.csv")
```

```{r}
# bind_rows with list
estimates <- bind_rows(list(popestimate_2010, popestimate_2015, popestimate_2020))
```

## Joining data

```{r}
maryland_ppp <- read_rds("class_04_demonstration.rds")
```

```{r}
naics_codes <- read_csv('naics_codes.csv')
```

```{r}
# with nrow included to match row total
maryland_ppp %>% left_join(naics_codes, by="naics_code") %>% select(name, naics_code, title) %>% nrow()
```

```{r}
# without nrow
maryland_ppp %>% left_join(naics_codes) %>% select(name, naics_code, title)
```

```{r}
# create new dataframe with title
maryland_ppp_with_title <- maryland_ppp %>% left_join(naics_codes)
```

```{r}
# zcta data
maryland_zcta <- read_csv('maryland_zcta.csv')
```

```{r}
# join on zip - but there's a problem
maryland_ppp_with_title_and_demographics <- maryland_ppp_with_title %>% left_join(maryland_zcta, by=c("zip"="ZCTA5N"))
```

```{r}
# let's fix the error
maryland_zcta <- maryland_zcta %>% mutate(across(ZCTA5N, as.character))
```

```{r}
# join works, but check the results
maryland_ppp_with_title_and_demographics <- maryland_ppp_with_title %>% left_join(maryland_zcta, by=c("zip"="ZCTA5N"))
View(maryland_ppp_with_title_and_demographics)
```

```{r}
# make a zip5 column and redo the join
maryland_ppp_with_title <- maryland_ppp %>% mutate(zip5 = str_sub(zip, 1, 5))
maryland_ppp_with_title_and_demographics <- maryland_ppp_with_title %>% left_join(maryland_zcta, by=c("zip5"="ZCTA5N"))
```

```{r}
# zcta with > 50% non-Hispanic Black population
maryland_ppp_with_title_and_demographics %>%
  filter(PNHB > 50) %>%
  summarize(
    count = n(),
    avgamount = mean(amount),
    medamount = median(amount))
```


```{r}
# zcta with > 50% non-Hispanic white population
maryland_ppp_with_title_and_demographics %>%
  filter(PNHW > 50) %>%
  summarize(
    count = n(),
    avgamount = mean(amount),
    medamount = median(amount))
```


```{r}
# zcta with > 50% non-Hispanic Black population grouped by rural/urban
maryland_ppp_with_title_and_demographics %>%
  filter(PNHB > 50) %>%
  group_by(rural_urban_indicator) %>%
  summarize(
    count = n(),
    avgamount = mean(amount),
    medamount = median(amount))
```

```{r}
# zcta with > 50% non-Hispanic white population grouped by rural/urban
maryland_ppp_with_title_and_demographics %>%
  filter(PNHW > 50) %>%
  group_by(rural_urban_indicator) %>%
  summarize(
    count = n(),
    avgamount = mean(amount),
    medamount = median(amount))
```
